# Generated by Django 3.2.9 on 2021-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_year', models.IntegerField(verbose_name='发行年份')),
                ('publish_date', models.DateField(verbose_name='日期')),
                ('region', models.CharField(max_length=100, verbose_name='地区')),
                ('title_original', models.CharField(max_length=100, verbose_name='电影名')),
                ('title_translated', models.CharField(max_length=100, verbose_name='电影名（中文）')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('topic', models.CharField(max_length=100, verbose_name='类型')),
                ('publisher', models.CharField(max_length=100, verbose_name='发行方')),
                ('media_score', models.FloatField(verbose_name='媒体评分')),
                ('filmarks_score', models.FloatField(verbose_name='filmarks观众评分')),
                ('yahoo_act_score', models.FloatField(verbose_name='yahoo表演评分')),
                ('yahoo_image_score', models.FloatField(verbose_name='雅虎画面评分')),
                ('yahoo_music_score', models.FloatField(verbose_name='雅虎音乐评分')),
                ('sells', models.FloatField(verbose_name='票房')),
                ('count', models.IntegerField(verbose_name='观影人数')),
                ('comment', models.CharField(max_length=1000, verbose_name='备注')),
            ],
        ),
    ]
