# Generated by Django 3.2.9 on 2021-11-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='count',
            field=models.IntegerField(null=True, verbose_name='观影人数'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, null=True, verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='filmarks_score',
            field=models.FloatField(null=True, verbose_name='filmarks观众评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='media_score',
            field=models.FloatField(null=True, verbose_name='媒体评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publish_date',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publish_year',
            field=models.IntegerField(null=True, verbose_name='发行年份'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publisher',
            field=models.CharField(max_length=100, null=True, verbose_name='发行方'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='region',
            field=models.CharField(max_length=100, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sells',
            field=models.FloatField(null=True, verbose_name='票房'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='topic',
            field=models.CharField(max_length=100, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yahoo_act_score',
            field=models.FloatField(null=True, verbose_name='yahoo表演评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yahoo_image_score',
            field=models.FloatField(null=True, verbose_name='雅虎画面评分'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='yahoo_music_score',
            field=models.FloatField(null=True, verbose_name='雅虎音乐评分'),
        ),
    ]
