# Generated by Django 3.2.9 on 2021-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20211120_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='publish_year',
            field=models.CharField(max_length=100, null=True, verbose_name='发行年份'),
        ),
    ]
